import type { Metadata } from 'next';

import { Inter, Playfair_Display } from 'next/font/google';

import QueryProvider from '@/components/query-provider';
import { ThemeProvider } from '@/components/theme-provider';
import '@/app/globals.css';
import { Toaster } from '@/components/ui/sonner';

type Props = Readonly<{ children: React.ReactNode }>;
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif'
});

export const metadata: Metadata = {
  description: 'Generated by Arsalan Ansari',
  title: 'Arsalan Ansari'
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.variable} ${playfair.variable} flex min-h-screen flex-col antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
